name: Build Release

on:
  release:
    types: [published]

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer

      - name: Install Composer Dependencies
        run: composer install --no-dev --prefer-dist

      - name: Dump Optimized Autoload
        run: composer dump-autoload --optimize

      - name: Create ZIP Archive
        run: |
          ZIP_NAME="${{ github.event.repository.name }}-${{ github.event.release.tag_name }}.zip"
          echo "Creating ZIP archive: $ZIP_NAME"
          zip -r "$ZIP_NAME" . -x "*.git*" "tests/*" "vendor/*/tests/*" "vendor/*/docs/*"

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ github.event.repository.name }}-${{ github.event.release.tag_name }}.zip
          asset_name: ${{ github.event.repository.name }}-${{ github.event.release.tag_name }}.zip
          asset_content_type: application/zip
